/**
 * pr.mjs—render the PR body (pure) and open the PR (git + gh). Only topic.json
 * is ever committed to the branch; the reported-pooled sidecar stays local, so
 * no derived/pooled value reaches the repo. The reported values appear ONLY in
 * the PR body, as a reviewer aid.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, rmSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { REPO_ROOT } from './env.mjs';

const fmt = (x) => (typeof x === 'number' && Number.isFinite(x) ? x.toFixed(3) : '—');

/**
 * Build the Markdown PR body. `ctx` = {
 *   topic, provenance, repro (ReproResult), audit: [{outcomeId, checks}],
 *   extractedOutcomes: [{id,label,k,patients,pooled}]
 * }. Pure and unit-tested.
 */
export function renderPrBody(ctx) {
  const { topic, provenance = {}, repro = { outcomes: [], pass: false }, audit = [], extractedOutcomes = [] } = ctx;
  const src = provenance.source || {};
  const lines = [];

  lines.push(`## ${topic.name} — auto-extracted, **REVIEW REQUIRED**`);
  lines.push('');
  lines.push(
    '> Extracted by DeepSeek from the source below. Do **not** trust blindly: verify every number against the paper before merging. No auto-merge; deploy fires only on merge to `main`.',
  );
  lines.push('');
  lines.push(
    `**Source:** ${src.title || topic.name}` +
      (src.pmid ? ` · PMID [${src.pmid}](https://pubmed.ncbi.nlm.nih.gov/${src.pmid}/)` : '') +
      (src.doi ? ` · DOI \`${src.doi}\`` : '') +
      (src.oa ? ' · open access' : ''),
  );
  lines.push('');

  // Extracted outcomes.
  lines.push('### Extracted outcomes (live engine pool)');
  lines.push('');
  lines.push('| Outcome | k | Patients | Live pooled |');
  lines.push('|---|---:|---:|---|');
  for (const o of extractedOutcomes) {
    const p = o.pooled ? `${o.pooled.measure || 'RR'} ${fmt(o.pooled.point)} [${fmt(o.pooled.ciLow)}–${fmt(o.pooled.ciHigh)}]` : '—';
    lines.push(`| ${o.label} | ${o.k ?? '—'} | ${o.patients ?? '—'} | ${p} |`);
  }
  lines.push('');

  // Reproduction gate.
  lines.push(`### Reproduction check — ${repro.pass ? '✅ PASS' : '❌ FAIL'}`);
  lines.push('');
  lines.push('Engine\'s independent re-pool vs the paper\'s reported pooled values. Reported values are **not** stored in the topic.');
  lines.push('');
  lines.push('| Outcome | Ours | Paper reported | Δ | Within tol |');
  lines.push('|---|---|---|---:|:--:|');
  for (const o of repro.outcomes) {
    const ours = o.ours ? `${fmt(o.ours.point)} [${fmt(o.ours.ciLow)}–${fmt(o.ours.ciHigh)}]` : '—';
    const rep = `${o.reported.point} [${o.reported.ciLow}–${o.reported.ciHigh}]`;
    lines.push(`| ${o.outcomeId} (${o.measure}) | ${ours} | ${rep} | ${o.pointDeltaPct}% | ${o.withinTol ? '✓' : '✗'} |`);
  }
  lines.push('');

  // Methods auditor.
  const flags = audit.flatMap((a) =>
    (a.checks || []).filter((c) => c.level === 'flag' || c.level === 'warn').map((c) => ({ ...c, outcomeId: a.outcomeId })),
  );
  lines.push('### Methods-auditor flags');
  lines.push('');
  if (flags.length === 0) {
    lines.push('_No warnings or flags raised._');
  } else {
    for (const f of flags) {
      lines.push(`- ${f.level === 'flag' ? '🚩' : '⚠️'} **${f.outcomeId}** — ${f.label}: ${f.detail}${f.value ? ` (${f.value})` : ''}`);
    }
  }
  lines.push('');

  // Provenance.
  const u = provenance.usage || {};
  lines.push('### Provenance');
  lines.push('');
  lines.push(
    `Model \`${provenance.model || 'deepseek-chat'}\` · tokens ${u.prompt_tokens ?? '?'} in / ${u.completion_tokens ?? '?'} out · est cost $${provenance.costUSD ?? '?'} · extracted ${provenance.extractedAt || ''}`,
  );
  lines.push('');
  lines.push('🤖 Auto-generated by the Ehvidence ingestion pipeline.');
  return lines.join('\n');
}

function git(args, opts = {}) {
  return execFileSync('git', args, { encoding: 'utf8', ...opts }).trim();
}

/**
 * Branch, copy the extracted topic into its repo location, commit ONLY that
 * file (never the gitignored sidecar), push, and open a PR. Returns
 * { prUrl, branch }. Throws on any git/gh failure (caller records `error`).
 *
 * `sourceTopicPath` is the queue/<pmid>/topic.json; it is copied to
 * src/content/topics/<slug>.json on the branch so the commit lands in the repo.
 */
export function openPr(slug, sourceTopicPath, bodyMarkdown, { base = 'main', dryRun = false } = {}) {
  const branch = `ingest/${slug}`;
  const repoRelPath = `src/content/topics/${slug}.json`;
  if (dryRun) {
    return { prUrl: `(dry-run) would open PR from ${branch} committing ${repoRelPath}`, branch, dryRun: true };
  }
  const startBranch = git(['rev-parse', '--abbrev-ref', 'HEAD']);
  git(['checkout', '-B', branch]);
  copyFileSync(sourceTopicPath, join(REPO_ROOT, repoRelPath));
  git(['add', repoRelPath]); // ONLY the topic file — never the sidecar
  git(['commit', '-m', `Ingest: ${slug} (auto-extracted, needs review)`]);
  git(['push', '-u', 'origin', branch, '--force-with-lease']);
  const bodyFile = join(tmpdir(), `ehvidence-pr-${slug}.md`);
  writeFileSync(bodyFile, bodyMarkdown);
  let prUrl = '';
  try {
    prUrl = execFileSync(
      'gh',
      ['pr', 'create', '--base', base, '--head', branch, '--title', `Ingest: ${slug} (review required)`, '--body-file', bodyFile],
      { encoding: 'utf8' },
    ).trim();
  } finally {
    rmSync(bodyFile, { force: true });
    git(['checkout', startBranch]); // leave the working tree where we found it
  }
  return { prUrl, branch };
}
